### PR TITLE
added warning when deleting parent article

### PR DESCRIPTION
**Pull request by ronachera**
A warning is shown when someone tries to delete a parent article.

### CODE REVIEW

**Comment by donni106** [comment]
Maybe you can resolve the conflict with `bundle update goldencobra`?

**Comment by ronachera** [comment]
isn't the Gemfile.lock normally part of .gitignore?

**Comment by donni106** [comment]
No, it is included to set versions globally.

**Comment by ronachera** [comment]
bundle update goldencobra resolves acts-as-taggable to 5.0.0 which depends on ruby >= 2.2.7 ...

**Comment by 5minpause** [comment]
I believe the release/1.5 branch runs on Ruby 2.2.1.
This would mean, that we'd need to set `acts-as-taggable < 5.0.0`, right?

**Comment by donni106** [comment]
Yes. `gem "acts-as-taggable-on", "~> 3.5.0"` or maybe `gem "acts-as-taggable-on", "~> 4.0.0"`?

**Comment by 5minpause** [comment]
Perhaps `gem "acts-as-taggable-on", ">= 3.5.0, < 5.0.0"`?

**Comment by ronachera** [comment]
dependency hell... now it cries for different versions of paper_trail, ruby and sass

**Comment by donni106** [comment]
We find a solution with fixing of its versions.

**Pull request merged**
