### PR TITLE
Create Code of Conduct file for GitHub

### PR DESCRIPTION
**Pull request by donni106**
The project should have a Code of Conduct file.
It is adapted from https://www.ikusei.de/agentur/code-of-conduct.

### CODE REVIEW

**Comment by 5minpause** [comment]
I just noticed. We could also use the latest version, not 1.0.0:
https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

**Comment by 5minpause** [comment]
Once done, we should open a PR here to be added to the list of projects:
https://github.com/ContributorCovenant/contributor_covenant

**Comment by donni106** [comment]
For this list https://www.contributor-covenant.org/adopters.html?

**Comment by 5minpause** [comment]
Yes, like this: https://github.com/ContributorCovenant/contributor_covenant/blob/master/README.md#adding-a-project-to-the-list-of-adopters

**Comment by donni106** [comment]
After merge the link to the Code of Conduct in https://github.com/ikuseiGmbH/Goldencobra/blob/master/CONTRIBUTING.md should point here.

**Comment by donni106** [comment]
PR for list of adopters:
https://github.com/ContributorCovenant/contributor_covenant/pull/466

**Pull request merged**
